name: Build Hook Docs

on:
 push:
   branches:
    - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use desired version of NodeJS
      uses: actions/setup-node@v4
      with:
          node-version-file: '.nvmrc'
    - name: Check versions
      run: npm -v; node -v
    - name: npm install, and build docs
      run: |
        npm install
        npm -g install gulp-cli
        npm run build:docs
      env:
        CI: true
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './docs-built'
