name: Node CI

on:
 push:
   branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and build docs
      run: |
        npm install
        npm run build:docs
      env:
        CI: true
  deploy:
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
    - env:
        BUILD_DIR = "docs/"
        secrets = ["GH_PAT"]
