name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
jobs:
  cypress:
    name: ${{ matrix.core.name }} ${{ matrix.php.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - {name: 'PHP Default', version: null}
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
        include:
          - php: {name: 'PHP Minimum', version: '7.4'}
            core: {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check versions
      run: npm -v; node -v

    - name: Install dependencies
      run: npm install

    - name: Composer install
      run: composer install

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }} ${{ matrix.php.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Log WP Environment Versions
      run: npm run env:version-log

    - name: Convert to multisite
      run: npm run to-multisite

    - name: Copy .htaccess
      run: npm run copy-htaccess

    - name: Test
      run: npm run cypress:run
