name: E2E Tests

on:
  push:
    branches:
      - develop
      - develop-v1
      - trunk
  pull_request:
    branches:
      - develop
      - develop-v1
jobs:
  cypress:
    name: ${{ matrix.core.name }} / ${{ matrix.php.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - {name: 'PHP Default', version: null}
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
        include:
          - php: {name: 'PHP 8.1', version: '8.1'}
            core: {name: 'WP stable', version: 'latest'}
          - php: {name: 'PHP 7.4', version: '7.4' }
            core: {name: 'WP minimum', version: 'WordPress/WordPress#5.2'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use desired version of NodeJS
      uses: actions/setup-node@v3
      with:
          node-version-file: '.nvmrc'
    - name: Check versions
      run: npm -v; node -v

    - name: Install dependencies
      run: npm install

    - name: Composer install
      run: composer install

    - name: Set the core version
      run: |
        ./tests/bin/set-core-version.js ${{ matrix.core.version }} ${{ matrix.php.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Log WP environment versions
      run: |
        npx wp-env run cli "wp core version"
        npx wp-env run cli "php --version"

    - name: Convert to multisite
      run: npm run to-multisite

    - name: Copy .htaccess
      run: npm run copy-htaccess

    - name: Test
      run: npm run cypress:run
