name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: NPM Install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use desired version of NodeJS
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
          node-version-file: '.nvmrc'

    - name: Cache Node
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm install

  cypress:
    name: ${{ matrix.core.name }} / ${{ matrix.php.name }}
    needs: [build]
    ## Pending upgrade of `@wordpress/env` package.
    continue-on-error: ${{ matrix.core.version == 'WordPress/WordPress#master' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - {name: 'PHP Default', version: null}
        core:
          - {name: 'WP stable', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#6.6'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
        include:
          - php: {name: 'PHP 7.4', version: '7.4'}
            core: {name: 'WP minimum', version: 'WordPress/WordPress#6.6'}
          - php: {name: 'PHP 8.1', version: '8.1'}
            core: {name: 'WP stable', version: 'latest'}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use desired version of NodeJS
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
          node-version-file: '.nvmrc'

    - name: Check versions
      run: npm -v; node -v

    - name: Cache Node
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      id: cache-composer
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      env:
        cache-name: cache-composer
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

    - name: Set PHP version
      uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
      with:
        php-version: ${{ matrix.php.version }}
        coverage: none
        tools: composer:v2

    - name: Composer install
      run: composer install

    - name: Build
      run: npm run build

    - name: Set the core version
      run: |
        ./tests/bin/set-core-version.js ${{ matrix.core.version }} ${{ matrix.php.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Log WP environment versions
      run: |
        npm run env run cli -- wp core version
        npm run env run cli -- php --version

    - name: Test
      run: npm run cypress:run

    - name: Update summary
      if: always()
      run: |
          npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
          rm -rf ./tests/cypress/reports/mochawesome-*.json
          npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
          npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
          cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY

    - name: Make artifacts available
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      if: failure()
      with:
        name: cypress-artifact-${{matrix.php.name}}-${{matrix.core.name}}
        retention-days: 2
        path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
            ${{ github.workspace }}/tests/cypress/reports/
