name: Generate ZIP

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Commit Ref (branch, tag, or hash)'
        required: false
        type: string

jobs:
  generate_zip:
    name: New ZIP file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ inputs.ref }}
      - name: Use desired version of NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set PHP version
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 7.4
          tools: composer:v2, wp
      - name: Check versions
        run: |
          npm -v
          node -v
          php -v
          composer -v

      - name: Install and build
        run: |
          composer install --no-dev
          npm install
          npm run release
          rm -rf ./release && unzip ${{ github.event.repository.name }}.zip -d ./release

      - name: Upload the ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: release
          retention-days: 5
