name: Generate ZIP

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Commit Ref (branch, tag, or hash)'
        required: false
        type: string

jobs:
  generate_zip:
    name: New ZIP file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Use desired version of NodeJS
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: '.nvmrc'

      - name: Set PHP version
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: 7.4
          tools: composer:v2, wp

      - name: Check versions
        run: |
          npm -v
          node -v
          php -v
          composer -v

      - name: Install and build
        run: |
          composer install --no-dev
          npm install
          npm run release
          npm run plugin-zip
          rm -rf ./release && unzip ${{ github.event.repository.name }}.zip -d ./release

      - name: Upload the ZIP file as an artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ github.event.repository.name }}
          path: release
          retention-days: 5
