name: Generate ZIP

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Commit Ref (branch, tag, or hash)'
        required: true
        type: string

jobs:
  generate_zip:
    name: New ZIP file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ inputs.ref }}
      - name: Use desired version of NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set PHP version
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 7.4
          tools: composer:v2
      - name: Check versions
        run: npm -v; node -v, php -v, composer -v

      - name: Install and build
        run: |
          composer install --no-dev
          npm install
          npm run makepot
          npm run plugin-zip

      - name: Upload the ZIP file as an artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.plugin_slug }}
          path: ${{ inputs.plugin_slug }}
          retention-days: 5
