name: Linting

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - develop
      - develop-v1
      - trunk
  pull_request:
    branches:
      - develop
      - develop-v1

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use desired version of NodeJS
      uses: actions/setup-node@v3
      with:
          node-version-file: '.nvmrc'
    - name: Cache Node
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ hashFiles('package-lock.json') }}
    - name: Check versions
      run: npm -v; node -v
    - name: npm install
      run: npm install
    - name: Generate linting report
      run: npm run lint:js -- --output-file eslint-report.json --format json
      continue-on-error: true
    - name: Annotate code linting results
      uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        report-json: 'eslint-report.json'
    - name: Update summary
      run: |
        npm_config_yes=true npx github:10up/eslint-json-to-md --path ./eslint-report.json --output ./eslint-report.md
        cat eslint-report.md >> $GITHUB_STEP_SUMMARY
      if: ${{ failure() }}
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set standard 10up cache directories
      run: |
        composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

    - name: Prepare composer cache
      uses: actions/cache@v2
      with:
        path: ${{ env.COMPOSER_CACHE }}
        key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ env.COMPOSER_VERSION }}-

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install --ignore-platform-reqs

    - name: Check PHPCS standard
      run: ./vendor/bin/phpcs -i

    - name: Check Compatibility of main plugin file.
      run: ./vendor/bin/phpcs ./distributor.php --runtime-set testVersion 5.6- --standard=PHPCompatibilityWP

    - name: PHPCS check
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 7.4-'
