name: Linting

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: assets/js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
    - name: composer install
      run: composer install --ignore-platform-reqs
    - name: Check PHPCS standard
      run: ./vendor/bin/phpcs -i
    - name: PHPCS check
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs .'
  vipcs:
    name: vipcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: VIPCS check
        uses: 10up/wpcs-action@v1.3.2
        with:
          enable_warnings: true
          standard: 'WordPress-VIP-Go'
          excludes: 'tests'
