name: Publish Release
on:
  release:
    types: [published]
jobs:
  zip:
    name: Attach ZIP asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Create ZIP
      run: |
        git archive --prefix=distributor/ HEAD -o distributor.zip

    - name: Upload release asset
      uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/distributor.zip
        asset_name: distributor.zip
        asset_content_type: application/zip
