name: Publish Release
on:
  release:
    types: [published]
jobs:
  zip:
    name: Attach ZIP asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create ZIP
      run: |
        rsync -rc --exclude={'.github','.git'} "$GITHUB_WORKSPACE/" "$GITHUB_WORKSPACE/distributor/" --delete --delete-excluded
        zip -rq "$GITHUB_WORKSPACE/distributor.zip" "distributor"
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/distributor.zip
        asset_name: distributor.zip
        asset_content_type: application/zip
