name: Release Pull Request Automation

on:
  create:
jobs:
  release-pull-request-automation:
    if: ${{ github.event.ref_type == 'branch' && contains( github.ref, 'release/' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate title
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo $BRANCH
          VERSION=${BRANCH#'release/'}
          echo "result="Release: ${VERSION}"" >> $GITHUB_OUTPUT
        id: title
      - name: Create Pull Request
        run: gh pr create --draft --title "${{ steps.title.outputs.result }}" --body-file ./.github/release-pull-request-template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
