name: Test

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  wpa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        snapshot: [
          "3593222a181f0f91824947dbd06985d5", # WP 4.9
          "9ea863cebfcbb416c6334a6bef6552f0", # WP 4.9 & Gutenberg 4.9
          "803989004f4b101a644ebfe9bb67e712", # WP 5.4
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v1

    - name: Install dependencies
      run: composer install

    - name: Setup WP Snapshots
      run: ./vendor/bin/wpsnapshots configure 10up --aws_key=${{ secrets.AWS_ACCESS_KEY_ID }} --aws_secret=${{ secrets.AWS_SECRET_ACCESS_KEY }} --user_name=wpacceptance --user_email=wpacceptance@10up.com

    - name: Test
      run: ./vendor/bin/wpacceptance run --snapshot_id=${{ matrix.snapshot }}

  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v1

    - name: Install dependencies
      run: composer install

    - name: PHPUnit
      run: './vendor/bin/phpunit'
