name: Test

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  wpa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        snapshot: ['wp-4.9', 'wp-4.9-gutenberg-4.9', 'wp-5.4.2']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v1

    - name: Install dependencies
      run: composer install

    - name: Setup WP Snapshots
      run: ./vendor/bin/wpsnapshots configure 10up --aws_key=${{ secrets.AWS_ACCESS_KEY_ID }} --aws_secret=${{ secrets.AWS_SECRET_ACCESS_KEY }} --user_name=wp-acceptance --user_email=travis@10up.com

    - name: Test
      run: ./vendor/bin/wpacceptance run --snapshot_name=${{ matrix.snapshot }}

  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        coverage: none
        tools: composer:v1

    - name: Install dependencies
      run: composer install

    - name: PHPUnit
      run: './vendor/bin/phpunit'
