name: PHPUnit Tests

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  phpunit:
    name: ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set standard 10up cache directories
        run: |
          composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

      - name: Prepare composer cache
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ env.COMPOSER_VERSION }}-

      - uses: getong/mariadb-action@v1.1

      - name: Set PHP version
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: phpunit-polyfills, composer:v2

      - name: Install dependencies
        run: composer update -W

      - name: Setup WP Tests
        run: bash tests/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1

      - name: PHPUnit
        run: composer run test
