name: "WordPress version checker"
on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
